/**
 * Created by PIZn on 16/1/11.
 */

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';

export const LOAD_USER_INFO = 'LOAD_USER_INFO';
export const LOAD_USER_INFO_SUCCESS = 'LOAD_USER_INFO_SUCCESS';
export const LOAD_USER_INFO_FAIL = 'LOAD_USER_INFO_FAIL';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

export const LOAD_REPO_INFO = 'LOAD_REPO_INFO';
export const LOAD_REPO_INFO_SUCCESS = 'LOAD_REPO_INFO_SUCCESS';
export const LOAD_REPO_INFO_FAIL = 'LOAD_REPO_INFO_FAIL';
export const LOAD_REPO_TREE = 'LOAD_REPO_TREE';
export const LOAD_REPO_TREE_SUCCESS = 'LOAD_REPO_TREE_SUCCESS';
export const LOAD_REPO_TREE_FAIL = 'LOAD_REPO_TREE_FAIL';
