/**
 * Created by PIZn on 16/1/11.
 */

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';
export const AUTH_LOGIN_DONE = 'AUTH_LOGIN_DONE';

export const LOAD_USER_INFO = 'LOAD_USER_INFO';
export const LOAD_USER_INFO_SUCCESS = 'LOAD_USER_INFO_SUCCESS';
export const LOAD_USER_INFO_FAIL = 'LOAD_USER_INFO_FAIL';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

export const LOAD_REPO_INFO = 'LOAD_REPO_INFO';
export const LOAD_REPO_INFO_SUCCESS = 'LOAD_REPO_INFO_SUCCESS';
export const LOAD_REPO_INFO_FAIL = 'LOAD_REPO_INFO_FAIL';
export const UPLOAD_REPO_INFO = 'UPLOAD_REPO_INFO';
export const LOAD_REPO_TREE = 'LOAD_REPO_TREE';
export const LOAD_REPO_TREE_SUCCESS = 'LOAD_REPO_TREE_SUCCESS';
export const LOAD_REPO_TREE_FAIL = 'LOAD_REPO_TREE_FAIL';

export const READ_REPO_TREE = 'READ_REPO_TREE';
export const READ_REPO_TREE_SUCCESS = 'READ_REPO_TREE_SUCCESS';
export const READ_REPO_TREE_FAIL = 'READ_REPO_TREE_FAIL';
export const READ_REPO_BLOB = 'READ_REPO_BLOB';
export const READ_REPO_BLOB_SUCCESS = 'READ_REPO_BLOB_SUCCESS';
export const READ_REPO_BLOB_FAIL = 'READ_REPO_BLOB_FAIL';
export const ADD_REPO_BLOB = 'ADD_REPO_BLOB';
export const ADD_REPO_BLOB_SUCCESS = 'ADD_REPO_BLOB_SUCCESS';
export const ADD_REPO_BLOB_FAIL = 'ADD_REPO_BLOB_FAIL';
export const REMOVE_REPO_BLOB = 'REMOVE_REPO_BLOB';
export const REMOVE_REPO_BLOB_SUCCESS = 'REMOVE_REPO_BLOB_SUCCESS';
export const REMOVE_REPO_BLOB_FAIL = 'REMOVE_REPO_BLOB_FAIL';

export const CLEAR_REPO_BLOB = 'CLEAR_REPO_BLOB';

export const UPDATE_REPO_BLOB = 'UPDATE_REPO_BLOB';
export const UPDATE_REPO_BLOB_SUCCESS = 'UPDATE_REPO_BLOB_SUCCESS';
export const UPDATE_REPO_BLOB_FAIL = 'UPDATE_REPO_BLOB_FAIL';

export const READ_REPO_BLOB_COMMIT = 'READ_REPO_BLOB_COMMIT';
export const READ_REPO_BLOB_COMMIT_SUCCESS = 'READ_REPO_BLOB_COMMIT_SUCCESS';
export const READ_REPO_BLOB_COMMIT_FAIL = 'READ_REPO_BLOB_COMMIT_FAIL';
